language: php

php:
  - 5.4
  - 5.5

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script:
  - ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml ./src/
  - phpunit

notifications:
  email:
    - lars.strojny@internations.org
    - max.beutel@internations.org
    - marc.jakubowski@internations.org
    - michael.weinrich@internations.org
    - vitor.balocco@internations.org
